/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Current message format for simulator app when storing messages in DynamoDB.
 */
export interface AppMessage {
  appId: "GPS" | "FLIP" | "TEMP" | "DEVICE";
  messageType: "HELLO" | "START" | "STOP" | "INT" | "GET" | "STATUS" | "DATA" | "OK" | "EVENT";
  /**
   * This number is incremented by one for each message transmitted
   */
  messageId?: number;
  ts?: number;
  data?: string;
  [k: string]: any;
}

export interface AppTimestreamMessage {
  [k: string]: string | number | boolean | string[] | number[];
  ts: number;
}
